### ISSUE TITLE
error in running main.py

### ISSUE THREAD

**Issue by notnick2** [CRAKZOR/linkedin-post-automator#10]
$ /bin/python /home/varun/auto/linkedin-post-automator/main.py
Traceback (most recent call last):
  File "/home/varun/auto/linkedin-post-automator/main.py", line 2, in <module>
    from core.content_manager import ContentManager
  File "/home/varun/auto/linkedin-post-automator/core/content_manager.py", line 2, in <module>
    from core.chatgpt import ChatGpt
  File "/home/varun/auto/linkedin-post-automator/core/chatgpt.py", line 7, in <module>
    class IncompleteResponse(openai.error.OpenAIError):
                             ^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'error'

**Comment by CRAKZOR** [comment]
Issue with newer version of openai. 

I use, openai == 0.27.8.

I'll update requirements.txt to fix this issue.
